branches:
  only:
  - master
language: scala
scala:
- 2.10.6
- 2.11.7
jdk:
- openjdk7
sudo: false
env:
  global:
  - secure: e2zFTxXtQSmdNB4VrM2aonddVpItJbPM7acvoaYyhYw0i6IIGjB/53ZgvXBjZBawlhjwI8OGw7UAalHUU9aRtQiyxFQaCKidLswQgAy6q5+ZgyXhnYJxY4Y0J8FNK1GLwtw+FaX10+jn6u6lgMRc9AS87LYUXq67mN9EBRu2HlrCHdKmfRRyOy2B8EewwtMdTGSvDVqLcwQi/N64amyPo97FF7PPlPcDkVzBO/PcZyTEO4sj09Al1vdXWo8ik3iUukEjVRZaFABPJMyk5EIGzyCcX16GJMa3oH6iBcoTsXbeW+MXXrDAY/AWt/S45x5sYAPw+utYEgmvx8VQF78D2LRPcon2RkefFYIU0qWCDheTXp2GU7QgRW2EYAgdvmXEI/uEdkGXc+fLoyAUUAP17MsamRaf2ahg6wBBfI+WVn3mbErFotu3GQtilxAVRcU/OI0jC4z9z2WfEHLr+g0C/d2Vxxp5R6GQf4TnCtoxVtCRxkj7i2G7FibYuMZXHeL7VY2SX9Vf9VqNoIOhgEb4yghX5DaPgmFXZQ41PpppUzvnkXStoXviriCHUqf4t7j/kPEKTkTqbK+/xI83HDwZlAv/UG1TC1Bq3pd8MDTFBOsa/d5bKrK4256zQr5as+N9BobUiF58wYQYF0wodV0IBlLCqksAZrq5cRdnnDQUB6Y=
  - secure: BjhPHYXr2Tmf2e0HkpqCMbj+uuzgojccee0Nvk1nhv4Ywp59ujqPy255o2eKaDoMRbz8KFKyb1tMgQEBhJJrb+nSRR6h1JvaDIvYh65a/IbpIeFj5MtsjbbkiSMgGTFQrqsGkstPORyRKNsOOyiQ8V6Fwjy4wEXBZbaknHIPjmSfwJaewWfv86U0pEHqN7HnCg6KRrIW/Pv2IVP1zu2VTxeeYYGfBKN4on2M0mHvEd1vA9zrj/cZ7kSoT36odV+fJ1Wu684h8TkCDQJ+dyTcDDRdgV4MTQfdRp2i468ssYbkWdtNJSfQKxDzLropjlCNpyFkd9p0w1kh3qHsl8W0hKFoIR6VWFukzBWP6qHJsbRH7/A60+smyQLOdBqxlpPbfLPNN4k1m+FPn1TD63QI9raoRX2CmK4LDWJv+l7trSNyeowDWIspMsSReBlwfNfuT0pv+8MCR2ZomLatq5jW3QjNjl9FWaJ29XLGcM7y34n3LBnPojiPBT/3iP6jUU4yI1V03MuBnMMneIZ28418fuYzMnjX3pqk+AJZDA9/FKOKLraVGw/DxTWzdqdKA4dop9+qmM8lrPWqcbikY3qyoOm1nS5o/pXIBVcFN3XSbnDgvKHxvEjIvQX+4KxD7X3o2dn2MpBaTDYhfUJEopCRJiIyDKn3JHXdh9RxFkdpf4I=
  - secure: cPsnRDy8uCNx5x1YhFO0FpMTwYcEz1HTWB/8N323orcyfwLlSt/IBPkqFz7seiaaa8Oz+pUcTv2idBo6y1OxfHJw8FfAnptQ0IKkQE3ir7bLSGNbk5tNvPc092dbAuj7JRqWMeFkWUpXxtG/8/AZWcZbBnP6f9PTmcWBBA1Zt0TGX68Wij6s/wDX27OMbNZhjxEvBbR4wlGLA3WJqfYDhyIrvUKPBQ+twkyxrjWAkSEzqHs6KGBcNxsmfXIoUh4oH1veSBuhpOKc7xqMC3LfMvgLY8NrY2KS+Zm75j9wLSVsPDusWOEy5rH2glfujtGuDJBPxlEvEOBTc/hq7IaKJur385ulX3rA5et01ORWWOJbq0E/VBgQ8acf0DUlIAZXxSp/tPSplVH+H/1O+wZhkIbhOlCi7ScFsswtRfo6WfZIhe3lcxSF55tvfVEKjwDspfwO+H5eXp1eeUcICiIoOHq9VLlUmBjfCUCu4/P19jux9eg9xOnUKkvYzb9QPFbgPalF9to0hkZplTX2lddgNXKT7BPKpZqfcqLaoPGF70OefkOencqyeBVVU/tTXBOefqEH3uVpQpwuY9uqP5SHCiEjohuZVaE0zNhZ7L/Y85rUTnJaKpi269ukVUCAgaquLltoRKQv8hcQB1W5+C251y9askt9j8ichiUiAiIJONs=
  - secure: Yy4J0fKoH/hoOX8uStv00NyZW/D2qw2kg8yYVnzsw65h/9BwHMEuXPIVfXJ5RMALatCJ18JePTbk+PV3Y2+TTfYGvzbr+1Xu6rFPIRNQFRQwIsr3aJ6apW1mDGHI8mqg97tGEfKf5/DxZ6d4F9jKOhfutz3w9PYMlkvtw7hmIvUTpWBxZAcyrdkIFBAZkpXaBGw0cpHR1pEg+uB1GkaeegnQTIQAPgza9FzNpIuKqdc0FU6jq4g0TPIqPM9Zi6pZFFk1Fl3xQisYniI8TR0Llv4aZujIeLZfauOVe2AYwmBgHg/Gv0+YKKLlXM7qK83vFUObLGrUoe6M9KxUzQO2LYW7TT2fzK8f4CoJAqyO9Ay07mHaAOAzpSLpB3ti4PhpLtqxR1NKcl/dVKXx/MDsD34rA1kyVdIhCzIwCedAGoZevik4UPco6ZJxbF8h1bU/UNiDdCoZyYbna7oJHptYkJCTxRXW8h6BnAVtsa/BGohG/uotSU5Xucl4FFj03P2Uhx7/N2ofT0d2BZLh6vDBFh91UP6MuFp1HdX2hBg9HpttarfL+I2pGwqlUPyE8xj/hFVxPMhzlrYDveC9dJLDLi1/FDtK9SYq5ro9X67r72E3ViKe7M2DhBfttxBfQ5Ts/HA71hZxbfULd2BwBNu2g1CcPd3S3inRXgjHFJaqPpY=
cache:
  directories:
  - ~/.ivy2
  - ~/travis-deps
  apt: true
before_install:
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/zookeeper | /bin/sh
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/kafka | /bin/sh
before_script:
  - ~/travis-deps/start-zookeeper.sh && sleep 3
  - ~/travis-deps/start-kafka.sh && sleep 3
script:
  - sbt -Dsbt.log.noformat=true -sbt-dir ~/.sbt ++$TRAVIS_SCALA_VERSION test it:test
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
