branches:
  only:
  - master
language: scala
scala:
- 2.11.11
- 2.12.2
jdk:
- oraclejdk8
sudo: false
env:
  global:
  # GIT_USER
  - secure: iLiK+KLpW54IGsT7Pe+Kac+v2ZhqS9Dnztat+TvroHGnwXMWbhECKx63mhJazrnmRvfkRMFvWr2Fq81JlEUeMCmv1Bj1ABIRtWBGIrJcN1H/Ys2b2rSloN/Wa6nVMhMh0sd2Rqw1xYk4Sg726iwDD3NUCSpARN4Jd9RFhLBNCyyYJ2/CxI34NInIyDQKvK7xdYfTex/aUshJqhRnvBkejR2ybiecOEFwtbJFnMiB1mnvZc9TmvlikstSZjiBDSeDTzaxoEyVStjSBWiYhw6mhCeXCESpwFPJ9taQZxxg7XSYRU4V6DpOxCjDPl7jg8N4WuP6vEumMt7lDGLCyksPblin4u25PnPzeo+3vWRvv5SpCNeHd8Q5Ze2tWLracLsW8gy4dA2+sz546cucWMdKl3FmRv2cL267I2OSktcMvPKr80TrcNhoktiMPO8AJS2/TgQrN2qTIZqMagJAlH7/6ObdzD1yY8aBNbBlQ6voGtvtvE+ZQRYhmhfnWlWwZepDgjL92hAcAFCjUV+mOVOTEr7SxKY/msJuuRjk5Y82PBVFM7bn/HbG5D7HJz2v5NLoX19SRxOaLn/0OxPANhCrJKySa7if+WcMjIy2EReLQqaDrT5DGs6zdrn2XPBUOD1DB3E2eW9doYyx9YTVeA01/cjwWLecBNNSQMqLB4bPWdw=
  # GIT_API_KEY
  - secure: s+ff+NyTQoC4V1cPQQ1Cr9CphR/dRjOb6gmvGsRI4803mbHt9WMGjsP1WsEoppk74KWbN/hOWdJTOTuk3gbW0oBbVhPfTyYRQp76tsfOKDrzGf8n5/s4p5OYFJJTJPkOcjmC1TdLDc9Ifk91QM6axdRU98jQGslF0Epbmdikuwrj0dn8DSyw+tMru+KR6bGwL54UTcGEGE1DJYA2i3De8zX3QIw4tlf+DI3f7iN+UHENEOGs98RxW9Rgc2G7XQDAaPUovj4oshCobfZLVmUCrlVle5mdMnYza6fP27CPSLVCKtYJAzIray5UBUzTrIyeH9OsQctNvHiEinHeZ0lwz+R6/rmEkdaYa3YkUKDUbufdHITumRUeKPLPjHDANt/wxwVrs4Sew9zrm6BrDTQRIqetsVwQ4bXnDLp19joU51NjPb66GpoQGHnSq/rL9A1EKj3Txy0/+Euv0CMSk0SZTzBf2+/DpJcdW5KsgRt2pz4OKoza6ZEBfaRbuTjGCZVEXeqriyH8e9iyQAk0olXqawT41mySLTYHO71+4b9Q7JERo+1/A+crdM+cBrgG/YyCqwrrhK7j7YdVo0siRL5eRb9Ok3cOQcGodJZ2Bkk8hh6w7zWnxd6GE+dDSKqIIDtM0PTlj0PnL6PAvP1/bSLjxw+YtOsQCa82w1SfjVJrTvM=
  # BINTRAY_API_KEY
  - secure: "ImyytaFEB5GzjX1wCad/biaalFeLEJ6h6WQh/t5A3+qj57VSL90QbDqpgjd3eaDFsxZtImU7BqM9jRP6aBgSshfPVaCBSY/SPN5TbUnMEq/hDce8TunHPFh+VCNXfyXLoUg0OwuGffhDx2OOYClTQnQmpPlXzwlrWIzqO4l6Px/P3V6OVWxjCvzjHKC5SRwZeS1J3ZuCBMKLwJ7gTetIuBF0Zvhrcz8bc066O35x4BBoozHULLR/IeUAEzazToVvwVw2Yk2lTBeg/VEAKls47r0ZjZtwVJwFQC4Agw7NPad+7NR0SisN1jdZcESvcaDH6DhK7PvmmfCJP9nrUFMGb6Z1htdf4LZ+qj8uB2DUfF0Zqf/aG5LQ4XXTV5iKpm1M5JP6IPmwCtAq3Cf2dryrYYqeaTEtYfsS7tLrsSyhvhRWOpaKswwWhmJ+NEFjBmpF5+cF8srG/qOONMNlryqUXWVao8rUT/b2tN65MNYkSKVWKF0EKuyB+j0paZBAIRt5xITd9JfdPNVlDN89nyUyi4jDHEVOs5hLKyocRi/Ln+SaSBSB36gQyrO41iKmJKxAfh0taaoXhHcZM7WaNo+fWHihlEmZfXckICrl+Di65zjbWv8XZUrDL5pwdQXbihGGfFxVDel8svk11CnWUroRC987cm5CpZSnVxKW0XCqT04="
  - BINTRAY_USER=pagerduty-admin
cache:
  directories:
  - ~/.ivy2
  - ~/travis-deps
  apt: true
before_install:
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/zookeeper | /bin/sh
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/kafka | /bin/sh
before_script:
  - ~/travis-deps/start-zookeeper.sh && sleep 3
  - ~/travis-deps/start-kafka.sh && sleep 3
script:
  - sbt -Dsbt.log.noformat=true -sbt-dir ~/.sbt ++$TRAVIS_SCALA_VERSION test it:test
after_script:
  - ~/travis-deps/kafka/kafka-server-stop.sh && sleep 3
  - sudo killall java consul mysqld && sleep 3 # Attempt to fix build hangs
after_success:
  - sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
