branches:
  only:
  - master
language: scala
scala:
- 2.10.6
- 2.11.7
jdk:
- openjdk7
sudo: false
env:
  global:
    - secure: "b0pT48ZaLOQpHK/2DzXU4LgPEOgrZKE92mqHdDkuVyflja6Y2lhxya7VRFSfP13NyA2K49tt+1WljKogqeVq6gRuZCbgFXZl4w8x6N+O/0CIi0lNvVQPqCTMkFBxknqTNU1Owk7BlJ9VUaxdj/w8SyjKYaCfgnw2pl0eHbuG7ga905ZwXQE3fUk5KkTHmrXGVoZ7Al64w8p+4ddsEcewJcWcicGFNa5ttdQjbxinyJkvsJYcSGqpkZq0gzhXt3gGXHz0OhpKkBClaGrPzZvLT8DKjvcxf7NrgBxRkb67a1MOYUVrIBq9qdK6SeNLuscLSujvT7r8Q7wxvsljM4vBCXrurGNCNN23WLT0u7qjkMFUSIDdGDuFMRxn9SMRS8hQNGs1U3HqOsxSWa4CffagmAK+IMKNMrYlPQlXcAf42VCp0XzpXfEFC7kAJIaEsP/82Ww7jlJBBjxOOogToMRfZoiaW2aS4fJ5rGihbvdEZ0+2jrLpxb30pHdvvwmN55eBfini7xnVAvj99IM+41/7VLuN4XDbH2arRZh1jOaeEBzTAcLsoJJy3ELUqviJJv3CILM++L4eIf8w4lF4cD1NnG5Th3YTKOJxRdQFgiUfcBNtocJtALYLY0Ow51WE/t0ds9ycQkkRWm4RKnp01FpNUKN9Qc1oGonRGLd9DDyJBj4="
cache:
  directories:
  - ~/.ivy2
  - ~/travis-deps
  apt: true
before_install:
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/zookeeper | /bin/sh
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/kafka | /bin/sh
  - cp .travisci/credentials.sbt ~/.sbt
  - sed -i "s|%{password}|$ARTIFACTORY_PASS|" ~/.sbt/credentials.sbt
before_script:
  - ~/travis-deps/start-zookeeper.sh && sleep 3
  - ~/travis-deps/start-kafka.sh && sleep 3
script:
  - sbt -Dsbt.log.noformat=true -sbt-dir ~/.sbt ++$TRAVIS_SCALA_VERSION test it:test
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
