branches:
  only:
  - master
language: scala
scala:
- 2.10.6
jdk:
- openjdk7
sudo: false
env:
  global:
    - secure: "kxT8D4FLeuRgAzzcJ7fgZUjiopPirCQuVQAK/84hKI/8ajrIq9ZFywD9iesDSqnuwRrkwYqRgH9sUs6DNeZFnmzdRCxhj8Zrz0m5T7OZ2f1Ff8hbCWn/Ob1/oSE7IV0V4UhZOdAuC/RRJDUhKqvzEk6bIOiahyhrfEkca/CDvWONwrFpNxItlQKpkMfgFLMGh9hXxwHto8Z2cD3qOjZmCHkchaaMxshqDX2a6UxPYxJ4a/Dp1IWTZF+aOHwM2YU9hfT1alh9jnFEOlL0y/ricKSFkS8RrAyO2CgVJ0jw4N0T8lV7l1C2JY/0PmAQE6X6qzw/w0fmFpAt0sCEESgWWYqangVZF0uO/twzMuVuDNaPzp1oKgHcBBs4Rx26FLCvA7sqBBHKA78irdFbeLirX0Cj6oZ6YrS2G+5HJOCbYzQ3lRdR7FBdcNhpuD0/vA3O1dGA7ObdRYi0O3497iBbzlQSHjUVVA8LuUBf5eygvWeKuH7iZHhQ9NFed9YyveyqxGIRvBO9IV1mAZZDsyzXunaPAL9Rm7JmhizfuhYWnKw2RCCj5ZmBSuRa7IgzGKfbGXQLBDIHPmqKiHQ8/gaTollVjaZTq0zVsrT2i4kvm9LP/FRkYFt+HcVR+LnaXSD+49yRJiagvW0X5PzIRoo36HMQG1rNQkTjE+xbK+JrC8k="
cache:
  directories:
  - ~/.ivy2
  - ~/travis-deps
  apt: true
before_install:
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/zookeeper | /bin/sh 
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/kafka | /bin/sh 
  - cp .travisci/credentials.sbt ~/.sbt
  - sed -i "s|%{password}|$ARTIFACTORY_PASS|" ~/.sbt/credentials.sbt
before_script:
  - ~/travis-deps/start-zookeeper.sh && sleep 3
  - ~/travis-deps/start-kafka.sh && sleep 3
sbt_args: "-Dsbt.log.noformat=true -sbt-dir ~/.sbt"
